{
 "title": "FastAPI",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "5xx Error Rate, %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(http_requests_total{status=\"5xx\"}) / sum(http_requests_total) * 100) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Errors by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (handler)(increase(http_requests_total{status=\"5xx\"}[$__range]))) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum by (handler) (increase(http_requests_total[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}